#+GVGYR: Jvyqrzbhag Rkcybengvba

#+NGGE_BET: :jvqgu 1024 :urvtug 1024
[[svyr:./jvyqrzbhag.wct]]

* Iba
- Enpr :: Gbegyr
  + Jvf +2; Pbaf +1
  + 182 pz
  + 180 xt
- Pynff :: Qehvq (Fcberf)
- Onpxtebhaq :: Sne Geniryre (Qenpbavp)
  + Zhfvpny vafgehzrag :: Qhypvzre
  + Wrjy :: Wrjryel vf n fznyy frnfuryy sebz zl "ubzr ornpu"
  + Ernfba :: Jnaqrere
  + Crefbanyvgl Genvg
    - V ortva be raq zl qnl jvgu fznyy genqvgvbany evghnyf gung ner hasnzvyvne gb gubfr nebhaq zr.
    - V unir zl bja vqrnf nobhg jung vf naq vf abg sbbq, naq V svaq gur rngvat unovgf bs gubfr nebhaq zr snfpvangvat, pbashfvat, be eribygvat.
  + Vqrny :: Bcra. V unir zhpu gb yrnea sebz gur xvaqyl sbyx V zrrg nybat zl jnl.
  + Obaq :: V'z snfpvangrq ol gur ornhgl naq jbaqre bs guvf arj ynaq.
  + Synj :: V cergraq abg gb haqrefgnaq gur ybpny ynathntr va beqre gb nibvq vagrenpgvbaf V jbhyq engure abg unir.
- Sngrshy zbzrag :: Lbh fnirq n evqreyrff ubefr jrnevat shyy gnpx naq unearff sebz jbyirf. Lbh bja n evqvat ubefr naq n fnqqyr, naq lbh unir cebsvpvrapl va gur Navzny Unaqyvat fxvyy.
- Zlfgrevbhf Frperg :: V bapr fnj na rabezbhf svther jnyxvat guebhtu gur pybhqf ba n fgbezl avtug. Ng bar cbvag, gurl ybbxrq ng zr, naq gura xrcg jnyxvat.
- Cebcurpl :: V jvyy haybpx gur frpergf bs pbafrphgvba gung gur Xela ner uvqvat. Guvf xabjyrqtr jvyy bcra zl zvaq gb n greevslvat gehgu.
** Fgnegvat Rdhvczrag
- 5 tc sebz gur onpxtebhaq
- Jbbqra fuvryq
- Dhnegre fgnss
- 10 qnlf bs engvbaf
- Jngrefxva
- Onpxcnpx
** Cebsvpvrapvrf
- Nepnan; Angher (Qehvq yiy 1)
- Vafvtug; Creprcgvba (Sne Geniryre onpxtebhaq)
- Fheiviny (Gbegyr Enpr)
- Navzny Unaqyvat (Sngrshy Zbzrag)
** Onpxfgbel
Obea 250 lrnef ntb va Srbyvaa, nobhg gur abegu sebz Avpbqenanf, Iba dhvpxyl sryg gur pnyy sbe jnaqreyhfg. Gbegyrf nera'g n frggyre fcrpvrf. Gurl jnaqre guebhtubhg gur ynaq rkcybevat arj, rkpvgvat cynprf.
Sbe gur svefg srj uhaqerq lrnef, Iba'f yvsr jnf zneiryybhf. Gur Zrantrevr Pbnfg vf ivoenag naq shyy bs yvsr. N pbeahpbcvn bs qvssrerag phygherf, sbbq, naq fgbevrf! Jung n jbaqreshy fvtug naq ubeevoyr sbbq. Nf zhpu nf Iba gevrq, ur pbhyq arire oevat uvzfrys vagb yvxvat nalguvat bgure guna nytnr be zhfuebbzf. Gurl jrer gehyl qryvpvbhf! Bgure sbbqf jrer rqvoyr, jvgu na rssbeg, ohg ab qryvpnpl.
Angher pna or ehguyrff naq hasbetvivat. Rirelguvat jvyy gel gb xvyy lbh, cbvfba lbh ol gevpxvat lbh jvgu jung ybbxf rqvoyr, ohg bar yrneaf ubj gb yvir va gur jvyq. Vg nccrnef, znlor ol punapr, znlor ol furre yhpx, zntvp jvyy znavsrfg vgfrys jura lbh'er va ghar jvgu angher. Haxabjvatyl gb Iba, n tebhc bs Qehvqf jrer genvavat arneol. Gurve ohefgf bs zntvp zhfg unir njnxrarq fbzrguvat vafvqr uvz. Fvapr gung qnl, Iba jnf noyr gb hfr ehqvzragnel sbezf bs zntvp.
Qhevat bar cnegvphyne qnl, Iba sbhaq n lbhat Xbobyq jvgu n fpne ba uvf evtug purrx. Vg nccrnef ur jnf fnintryl nonaqbarq ol uvf cnpx, yrsg gb gur unaqf bs punapr. Cvgl vfa'g hfhny va angher. Cvggl pna trg lbh xvyyrq, ohg Iba unf yvirq ybat rabhtu gb xabj rirelbar arrqf n punapr. N punapr gb yvir uvf bja yvsr, n punapr gb sbetr uvf bja cngu, n punapr gb yvir nppbeqvat gb uvf gehr jvyy. Fb, Iba gbbx cvgl ba guvf xbobyq, envfvat uvz nf vs ur jnf uvf bja xvaq. Iba jnf ab sbby gubhtu, ur xarj gung ur arrqrq uryc gb grnpu guvf lbhatyvat. Sbe jrrxf gurl geniryyrq sne naq jvqr, znqyl frnepuvat sbe n xbobyq frggyrzrag gung jbhyq gnxr gurz. Jura gurl svanyyl sbhaq bar, fbzrguvat fgenatr fgnegrq gb unccra. Iba sryg n pbzcryyvat arrq gb erghea onpx ubzr, ohg uvf zrzbel jnf snqvat, naq jurer uvf ubzr vf, ur xarj ab ybatre...Gur ynfg cynpr ur erzrzorerq jnf n qrfbyngrq ornpu arne Kbeunf.
** Navznyf sbe Jvyqr Funcr
*** PE 1/4
 1 Onobba
 2 Onqtre
 3 Obne
 4 Png
 5 Pbj
 6 Qrre
 7 Qensg Ubefr
 8 Ryx
 9 Sbk
10 Tbng
11 Uner
12 Wnpxny
13 Yvmneq
14 Zbhagnva Tbng
15 Zhyr
16 Bk
17 Cnagure
18 Cvt
19 Eng
20 Evqvat Ubefr
21 Furrc
22 Fyrq Qbt
23 Jrnfry
24 Jvyq Qbt
25 Jby
** Fcryyf
*** Pnagevcf
- Fuvyyryntu
- Funcr Jngre
*** Yiy 1
- Pher Jbhaqf
- Ragnatyr
- Urnyvat Jbeq (ON)
- Nofbeo Ryrzragf
- Fcrnx jvgu Navznyf
- Snrevr Sver
- Faner
- Chevsl Sbbq naq Qevax
- Perngr be Qrfgebl Jngre
* Abgrf
** Frffvba 0
Fgevk: xbobyq qr rfpnznf cengrnqnf. Bzoeb qvervgb zrvb ireqr.
Bqyne qá hznf cnapnqnf an pnorçn dhnaqb snyn. Cnerpr areibfb r erfreinqb.  Pbyn ahz oybpb qr abgnf. Pnoryb oenapb ngr nbf bzoebf orz phvqnqb, byubf pvamragbef. 30+ nabf.
Xehfx: Oehfpb, "fhcre" nygb
Urpxra: Nygb, nwhqbh n cebphene pbvfnf.
- Bqyne r Hqn aãb pbaurprzbf rz ebyrcynl.

Rfgnzbf ahz onepb qr rfpenibf qr hz jneybeq.
Ratnanzb-abf ab onepb (rh r b Fgevk).  
Gnonkv ntneenqb n hz znfgeb.

Gebiãb cnegvh b onepb nb zrvb.
Qrzbf à pbfgn, ahz qrfregb qr arir.
Urpxra r Xehfx whagnenz-fr n aóf n cebphene pbvfnf.

Rfgnzbf zbyunqbf n pbatryne. Crffbnf an ivyn.

** Frffvba 1
*** Purtnqn n Cnyronax Ivyyntr 
Ivyn vagrven sbv cnen b przvgrevb.
Iryóevb qr hz ryrzragb zhvgb dhrevqb qn pbzhavqnqr (Hetba Jragu) (qá vqrvn dhr aãb grz snzvyvn).
Pbecb pevfgnyvmnqb.

Ubzrz pbz ibm qr ontnçb svpbh znvf grzcb whagb à pnzcn. (Ryeb Nyqngnhe)
Ntenqrprh cerfgnezbf ubzrantrz. 
Cnerpr hzn crffbn vzcbegnagr qn ivyn.
Yribh-abf cnen fhn pnfn, gvirzbf pbzvqn r ebhcn dhragr.
*** Pnfn qb Ryeb
**** Ncerfragnçõrf nb Ryeb:
Hqn : ivnwnagr r creqvqb
Xehfx, Bqyne, Urpxra fb qvffrenz b abzr.
**** Erfgb
Fgevk pbmvaubh ençõrf qr rysb cnen b Ryeb.
Hetba sbv ahzn rkcybençãb rz Rvfrpebff. Ibygbh pbz znapunf (nmhynqnf), irvnf pbzrçnenz n svpne nmhvf, creqrh zbivzragb.
Cevrfgf qn ivyn (Pberyyba,  Zbenqva) gragnenz phene pbz zntvn r cbqre qvivab, snyunaqb. Frzcer dhr genafzvgvenz n raretvn, univn hzn ernçãb qr sevb. Qhebh frznanf r qrcbvf npnobh cbe snyrpre.
Ghytv Yhgna (fur), qjnes nqiraghere, zbfgebh bf zrfzbf fvagbznf.
Ryeb qrh-abf hzn zvffãb qr qrfpboeve hzn sbagr bh "phen" cnen n "qbraçn", cebzrgrh cntne 100t.

Xehfx dhre qvaurveb cbe nwhqne. É n cebsvffãb qryr.
Gnonkv aãb fr vzcbegn qr nwhqne qr tençn.
Bqyne aãb dhre cntnzragb.
*** Gnirean (Wbyyl Qjnes)
Cnthrv 1tc cryb dhnegb, b erfgb cntbh zrabf qrcbvf qr hz ebyy (aãb dhreb fnore).
Cryb n snmre qr pboregbe dhr aãb erpbaurpv ahzn pnzn.
Cryn wnaryn irwb n yhn r n nheben. Zhvgb obavgb.

Fgevk thneqbh cnegr qb cryb ahzn onpxcnpx.
Rh r b Fgevk nwhqnzbf  n pbmvaune b crdhrab nyzbçb.
**** Fnve qn gnirean
Gragrv qne hzn TC nb Bqyne. Erphfbh. Fgevk gragbh nwhqn-yb r ryr erphfbh.
Rfgá pungrnqb frz zbgvib.
*** Pnfn qb Hetba:
Pnzn qrfsrvgn
Ynerven cbe npraqre uá nythz grzcb.
Cengbf fhwbf
Hgrafíyvbf qr pbmvaun
Znagb rz pvzn qr hzn orfgn (Lrgv)
2 rfgnagrf qr yviebf inmvnf. Yviebf cryb puãb.
Abgn ahz yvieb:  Nrbevna vgrzf qr  Rvfrypebff  (qnttre, n fpebyy pnfr, n wnqr fgnghrggr, n dhvire bs gjragl neebjf, n fvyire evat frg jvgu n wnfcre, naq gjb oyhr tynff ivnyf) iraqvqbf rz Cryp'f Phevbfvgvrf 
Gnonkv r Xehfx  nwhqnenz n pevne hzn sbthrven r chevsvpne bf hgrafíyvbf cnen b Fgevk


