#+TITLE: Wildemount Exploration


Born 250 years ago in Feolinn, about the north from Nicodranas, Von quickly felt the call for wanderlust. Tortles aren't a settler species. They wander throughout the land exploring new, exciting places.
For the first few hundred years, Von's life was marvellous. The Menagerie Coast is vibrant and full of life. A cornucopia of different cultures, food, and stories! What a wonderful sight and horrible food. As much as Von tried, he could never bring himself into liking anything other than algae or mushrooms. They were truly delicious! Other foods were edible, with an effort, but no delicacy.
Nature can be ruthless and unforgiving. Everything will try to kill you, poison you by tricking you with what looks edible, but one learns how to live in the wild. It appears, maybe by chance, maybe by sheer luck, magic will manifest itself when you're in tune with nature. Unknowingly to Von, a group of Druids were training nearby. Their bursts of magic must have awakened something inside him. Since that day, Von was able to use rudimentary forms of magic.
During one particular day, Von found a young Kobold with a scar on his right cheek. It appears he was savagely abandoned by his pack, left to the hands of chance. Pity isn't usual in nature. Pitty can get you killed, but Von has lived long enough to know everyone needs a chance. A chance to live his own life, a chance to forge his own path, a chance to live according to his true will. So, Von took pity on this kobold, raising him as if he was his own kind. Von was no fool though, he knew that he needed help to teach this youngling. For weeks they travelled far and wide, madly searching for a kobold settlement that would take them. When they finally found one, something strange started to happen. Von felt a compelling need to return back home, but his memory was fading, and where his home is, he knew no longer.
